# Services are enabled via configuration, hence the twig.extension tag is not
# added in these services.
services:

# Fabien Potencier' Twig Extensions
    dms_twig_extension.fabpot.array:
        class: Twig_Extensions_Extension_Array

    dms_twig_extension.fabpot.date:
        class: Twig_Extensions_Extension_Date
        arguments:
            - "@translator"

    dms_twig_extension.fabpot.i18n:
        class: Twig_Extensions_Extension_I18n

    dms_twig_extension.fabpot.intl:
        class: Twig_Extensions_Extension_Intl

    dms_twig_extension.fabpot.text:
        class: Twig_Extensions_Extension_Text

# DMS Twig Extensions
    dms_twig_extension.dms.textual_date:
        class: DMS\Bundle\TwigExtensionBundle\Twig\Date\TextualDateExtension
        arguments:
            - "@translator"
            
    dms_twig_extension.dms.pad_string:
        class: DMS\Bundle\TwigExtensionBundle\Twig\Text\PadStringExtension
