language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=^2
    - php: 7.1
      env: SYMFONY_VERSION=^2
    - php: 5.6
      env: SYMFONY_VERSION=^3
    - php: 7.1
      env: SYMFONY_VERSION=^3

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update -q
  - if [[ "$TRAVIS_PHP_VERSION" != 7.1* ]]; then echo "removing lock file" && rm composer.lock; fi;
  - composer install
  - if [ "$SYMFONY_VERSION" != "" ]; then echo "installing symfony ${SYMFONY_VERSION}" && composer require "symfony/symfony:${SYMFONY_VERSION}" --update-with-dependencies; fi;

script: ./vendor/bin/phpunit --coverage-text
